"""fix user3

Revision ID: 024f7eea1177
Revises: c9d01ad02cf0
Create Date: 2022-09-14 16:12:14.695567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024f7eea1177'
down_revision = 'c9d01ad02cf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
