"""“initdb”

Revision ID: 05f77d921df7
Revises: 45c3d1fc3264
Create Date: 2022-09-06 15:30:20.009976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f77d921df7'
down_revision = '45c3d1fc3264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
