"""init db

Revision ID: 0947d69ce5c5
Revises: 
Create Date: 2022-09-14 18:43:35.064612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0947d69ce5c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False, comment='省/直辖市'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='国家'),
    sa.Column('country_code', sa.String(length=100), nullable=False, comment='国家代码'),
    sa.Column('country_population', sa.BigInteger(), nullable=False, comment='国家人口'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province')
    )
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    op.create_table('data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='所属省/直辖市'),
    sa.Column('date', sa.Date(), nullable=False, comment='数据日期'),
    sa.Column('confirmed', sa.BigInteger(), nullable=False, comment='确诊数量'),
    sa.Column('deaths', sa.BigInteger(), nullable=False, comment='死亡数量'),
    sa.Column('recovered', sa.BigInteger(), nullable=False, comment='痊愈数量'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_id'), 'data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_id'), table_name='data')
    op.drop_table('data')
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
