"""fix user

Revision ID: 1b0467680db2
Revises: 5b11ae1c651a
Create Date: 2022-09-14 15:45:26.321535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b0467680db2'
down_revision = '5b11ae1c651a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_ibfk_1', 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    op.add_column('user', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'book_id')
    op.add_column('book', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_ibfk_1', 'book', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
