"""fix user34

Revision ID: 29b401b75309
Revises: 024f7eea1177
Create Date: 2022-09-14 16:34:15.772319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b401b75309'
down_revision = '024f7eea1177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_ibfk_1', 'data', type_='foreignkey')
    op.create_foreign_key(None, 'data', 'city', ['city_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.create_foreign_key('data_ibfk_1', 'data', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###
