"""fix user2

Revision ID: c9d01ad02cf0
Revises: 30804b5e010c
Create Date: 2022-09-14 16:00:01.428136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d01ad02cf0'
down_revision = '30804b5e010c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
